# Generated by Django 4.0.4 on 2024-03-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUcesTFE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Globales_Editables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Variable',
            new_name='VariableBD',
        ),
    ]
