# Generated by Django 4.0.4 on 2024-03-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUcesTFE', '0002_datos_globales_editables_rename_variable_variablebd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='precision',
            field=models.CharField(max_length=50),
        ),
    ]
