# Generated by Django 4.0.4 on 2024-07-06 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppUcesTFE', '0005_proyecto_cuadrante1_proyecto_cuadrante2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizCuadrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppUcesTFE.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoMatrizCuadrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField()),
                ('columna', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('matrizCuadrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUcesTFE.matrizcuadrada')),
            ],
        ),
    ]
