# Generated by Django 4.0.4 on 2024-07-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUcesTFE', '0007_remove_variablebd_dependencia1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proyecto', models.ManyToManyField(to='AppUcesTFE.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Fortaleza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proyecto', models.ManyToManyField(to='AppUcesTFE.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Debilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proyecto', models.ManyToManyField(to='AppUcesTFE.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Amenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proyecto', models.ManyToManyField(to='AppUcesTFE.proyecto')),
            ],
        ),
    ]
